version: "3.9"
services:
  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_DB: "postgredb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"