spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgredb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    default-schema: public
