CREATE TABLE exchange_rate
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    currency            VARCHAR(255),
    rate_tousd          DECIMAL,
    date                date,
    close_rate          DECIMAL,
    previous_close_rate DECIMAL,
    CONSTRAINT pk_exchangerate PRIMARY KEY (id)
);
